name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide a minimal reproducible case.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Numbered steps
      placeholder: |
        1. Configure provider...
        2. Run command...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. main@commit or v0.1.0

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: macOS/Linux, Node version, provider/model
